[project]
name = "mcp-proto"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "mcp>=1.2.0",
  "pandas>=2.2.0",
  "pyarrow>=15.0.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
